### ISSUE TITLE
No longer builds against Prom master

### ISSUE THREAD

**Issue by justincormack** [docker/go-metrics#12]
Getting
```
../../docker/go-metrics/timer.go:39: cannot use lt.m.WithLabelValues(labels...) (type prometheus.Observer) as type prometheus.Histogram in field value:
	prometheus.Observer does not implement prometheus.Histogram (missing Collect method)
```

**Comment by roadrunner** [comment]
@justincormack, I had the same compile error, it fixed after cleanup vendored packages.

**Comment by stevvooe** [comment]
Note this was caused by https://github.com/prometheus/client_golang/pull/285.

The current fix in place doesn't preserve the abstraction of the go-metrics package, so I'm re-opening this.
